### PR TITLE
Update to version 4.7

### PR DESCRIPTION
**Pull request by magna-z**

### CODE REVIEW

**Comment by dough29** [comment]
Thank you, sorry for being too fast and not seeing some mistakes :+1:

**Comment by tananaev** [comment]
By the way, version 4.8 is also out. It has some important bug fixes.

**Comment by dough29** [comment]
Good news !

I'll look how Docker Hub is handling tags so we can, for example, create a "generic" tag like "4-alpine" so it always take us to the latest 4.x version . Less work for consumers but maybe the same on this repo :-)

**Comment by dough29** [comment]
@tananaev : maybe we can create new build rules on Docker Hub like this :

Global version :
- Source type : `branch`
- Source : `/^v?(\d+)\./` so we can extract first figure from branch name like `4.4` or `v4.5`
- Docker tag : `{\1}` or `v{\1}`
- Dockerfile location : `alpine`

Alpine explicit version :
- Source type : `branch`
- Source : `/^v?(\d+)\./`
- Docker tag : `{\1}-alpine` or `v{\1}-alpine`
- Dockerfile location : `alpine`

Debian version :
- Source type : `branch`
- Source : `/^v?(\d+)\./`
- Docker tag : `{\1}-debian` or `v{\1}-debian`
- Dockerfile location : `debian`

**Comment by magna-z** [comment]
> @tananaev : maybe we can create new build rules on Docker Hub like this :
> 
> Global version :
> 
> * Source type : `branch`
> * Source : `/^v?(\d+)\./` so we can extract first figure from branch name like `4.4` or `v4.5`
> * Docker tag : `{\1}` or `v{\1}`
> * Dockerfile location : `/alpine/`
> 
> Alpine explicit version :
> 
> * Source type : `branch`
> * Source : `/^v?(\d+)\./`
> * Docker tag : `{\1}-alpine` or `v{\1}-alpine`
> * Dockerfile location : `/alpine/`
> 
> Debian version :
> 
> * Source type : `branch`
> * Source : `/^v?(\d+)\./`
> * Docker tag : `{\1}-debian` or `v{\1}-debian`
> * Dockerfile location : `/debian/`

Current build rules in DockerHub:
image

In all rules used version-branch because on branch we can create new commits with build fix.

**Comment by dough29** [comment]
The idea is to create a "latest" Docker image for current major version.

With my suggestion we can use `traccar/traccar:4` or `image: traccar/traccar:4-alpine` from Docker Hub instead of fixed `image: traccar/traccar:4.8-alpine`

Users wont have to modify their Docker Compose file to get minor versions.

**Comment by magna-z** [comment]
> The idea is to create a "latest" Docker image for current major version.
> 
> With my suggestion we can use `traccar/traccar:4` or `traccar/traccar:4-alpine` from Docker Hub instead of fixed `traccar/traccar:4.8-alpine`
> 
> Users wont have to modify their Docker Compose file to get minor versions.

Thank you for this idea.
I am add this rules in DockeHub build settings.

**Comment by dough29** [comment]
Thanks a lot for your work !

**Pull request merged**
