### PR TITLE
Always get latest build

### PR DESCRIPTION
**Pull request by dough29**

### CODE REVIEW

**Comment by dough29** [comment]
I tried to simplify the command line but grep version on Alpine is too light, can't find a way to extract a group...

I have this working for the Debian one :

`curl --silent "https://api.github.com/repos/traccar/traccar/releases/latest" | grep -Po '"browser_download_url": "\K.*(other).*?(?=")'`

Let me know if you want to have same line on both file or if you want me to push the simplified one for Debian.

**Comment by magna-z** [comment]
1) The current gitFlow, when static version used as branch name, is needed for building docker as "Automated Build".
2) Static version use in README.md and update by current gitFlow together with Dockerfile`s.

**Comment by dough29** [comment]
Thank you for your answer.

So as I understand the docker hub is tracking this GitHub repo to fetch new release ?

**Comment by magna-z** [comment]
Yes, it`s "Automated Build" on Docker Hub - https://docs.docker.com/docker-hub/builds/

**Pull request closed without merging**
