### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hunter-hunter**
Add a line for creating a presistent data folder on the host. This should be standard since recreating the container would erase the data folder otherwise

### CODE REVIEW

**Comment by tananaev** [comment]
I think the recommendation is to use proper database, like MySQL. You should never use default H2 for production.

**Comment by hunter-hunter** [comment]
I totally agree that's the intent but the documentation that's around the internet doesn't make that clear. There are people who are run the most basic Docker run command they see and if everything works as-is there's a significant portion who won't revisit what the "correct" way would be.

Alternatively, could the documentation [here](https://www.traccar.org/docker/) be updated to explicitly state that the default H2 database shouldn't be used outside of testing and mention that not adding a bind mount will cause the database to be lost on container recreation?

I could also update this pull request to say something similar rather than change the existing Docker run command.

**Comment by magna-z** [comment]
I think this volume may not be out of place if the database connection is not configured in the configuration file. Otherwise, it just leaves the directory empty.

**Comment by hunter-hunter** [comment]
Based on my experience, the H2 database still uses the data folder which is the reason that people will lose their configuration when the container is restarted. I'm not quite sure how the data is persisting through `docker container restart traccar` but recreating the container definitely wipes out the data folder.

You should be able to recreate by creating a docker-compose file

```
version: '2'

services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: always
    ports:
      - 8082:8082
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp 
    volumes:
      - ~/appdata/traccar/logs:/opt/traccar/logs:rw
      - ~/appdata/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro
```

Run `docker-compose up -d` and register a user. Running `docker exec -it /bin/sh` followed by `du -sh /opt/traccar/data` should return ~1-2MB. 

You'll continue to get the same value after running `docker-compose restart`, but if you run `docker-compose up -d --force-recreate` you won't be able to log in anymore and running `du -sh /opt/traccar/data` will return ~100kB

**Comment by tananaev** [comment]
Let's update README with a separate section about database. What do you think?

**Comment by hunter-hunter** [comment]
Okay that works for me, the README is now updated to include clarification on the database use

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
